name = "meshsdk/aiken-template"
version = "0.0.0"
compiler = "v1.0.31-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'meshsdk/aiken-template'"

[repository]
user = "meshsdk"
project = "aiken-template"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.0.1-beta"
source = "github"
