# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches:
      - feature/wasm
  pull_request:
    branches:
      - feature/wasm

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn && cargo install wasm-pack
      - run: |
          if [[ "${{ github.event.head_commit.message }}" =~ ^(docs:|chore:|rust:) ]]; then
              echo "Skipping npm publish due to commit message."
          else
              yarn && yarn js:publish-nodejs && yarn js:publish-browser
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
